Logging into ecr

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,9 +46,9 @@ jobs:
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
         envs: |
-          TAG=${{ env.TAG }}
-          AWS_REGION=${{ secrets.AWS_REGION }}
-          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
+          TAG=${{ env.TAG }}  # Using env context for TAG
+          AWS_REGION=${{ secrets.AWS_REGION }}  # Ensure AWS_REGION is in secrets
+          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}  # Ensure AWS_ACCOUNT_ID is in secrets
         script: |
           export TAG="${{ env.TAG }}"
           export AWS_REGION="${{ secrets.AWS_REGION }}"
@@ -58,3 +58,13 @@ jobs:
           echo "TAG: ${TAG}"
           echo "AWS_REGION: ${AWS_REGION}"
           echo "ACCOUNT_ID: ${ACCOUNT_ID}"
+
+          echo "Logging in to Amazon ECR..."
+          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}
+
+          if [ $? -eq 0 ]; then
+            echo "Successfully logged in to Amazon ECR."
+          else
+            echo "Failed to log in to Amazon ECR."
+            exit 1
+          fi
